# frozen_string_literal: true

# Migration for BlogComments, generated by rails g model BlogComment.
class CreateBlogComments < ActiveRecord::Migration[6.0]
  def change
    create_table :blog_comments do |t|
      t.string :name
      t.text :body
      t.references :blog_post, null: false, foreign_key: true

      t.timestamps
    end
  end
end
