# frozen_string_literal: true

# Migration for CreateBlogPost, generated by rail g model CreateBlogPost.
class CreateBlogPosts < ActiveRecord::Migration[6.0]
  def change
    create_table :blog_posts do |t|
      t.string :title
      t.text :body

      t.timestamps
    end
  end
end
